Test and document 'autoinit' module command

diff --git a/testsuite/bin/install_test_csh b/testsuite/bin/install_test_csh
--- a/testsuite/bin/install_test_csh
+++ b/testsuite/bin/install_test_csh
@@ -62,14 +62,28 @@ switch ($shkind)
       set shopts=''
 endsw
 
-if ( ! -r $initfile ) then
+# init module via autoinit cmd if modulecmd.tcl is initfile
+if ( "`basename $initfile`" == 'modulecmd.tcl' ) then
+   set autoinit=0
+else
+   set autoinit=1
+endif
+
+if ( $autoinit == 0 && ! -x $initfile ) then
+   echo "ERROR: Cannot execute $initfile"
+   exit 1
+else if ( $autoinit != 0 && ! -r $initfile ) then
    echo "ERROR: Cannot read $initfile"
    exit 1
 endif
 
 # source module init file if first step of given mode
 if ( "$mode" == 'top' || "$mode" == 'sub' ||  "$mode" == 'subsub' ) then
-   source $initfile
+   if ( $autoinit == 0 ) then
+      eval `$initfile $shname autoinit`
+   else
+      source $initfile
+   endif
 endif
 
 # execute command list or perform recursive call
